# -*- coding:utf-8 -*-


class ClientPackagePrefixes():

    CLIENT_WANTS_TO_USE = "AAH"
    CLIENT_WANTS_TO_WEAR_ITEM = "AAF"
    CLIENT_SENDS_LOGIN_MESSAGE = "LGN"
    CLIENT_SENDS_FINISHED_DESCRIPTION = "AAE"
    CLIENT_WANTS_TO_CRAFT = "AAD"
    CLIENT_WANTS_TO_MOVE_ITEM = "AAC"
    CLIENT_WANTS_CLOSE_CONTAINER = "AAB"
    CLIENT_WANTS_OPEN_CONTAINER = "AAA"
    CLIENT_SENDS_TTL = "TTL"
    CLIENT_WANTS_TO_MOVE = "MOV"