# -*- coding:utf-8 -*-


class ServerPackagePrefixes():

    CHARACTER_CONDITION_PROPERTIES = "026"
    GUARD_DENYS_ACCESS = "025"
    AT_NEW_LEVEL = "024"
    ENEMY_STARTS_ATTACK_MESSAGE = "023"
    PLAYER_LEFT_AREA = "022"
    ITEM_TRANSFER_NOT_WORKED = "021"
    WORLD_OBJECT_DELETE_MESSAGE = "020"
    BULLET_DESTRUCTION_MESSAGE = "019"
    BULLET_UPDATE_MESSAGE = "018"
    ENEMY_INFO = "017"
    NPC_INTERACTION = "016"
    USING_RESULT_MESSAGE = "015"
    ITEM_DELETE_COMMAND = "014"
    PLAYER_MOVING_INFO = "013"
    ITEMS_USES_UPDATE_COMMAND = "012"
    WEARING_MESSAGE = "010"
    UNWEARING_MESSAGE = "011"
    STEPABLE_UPDATE = "009"
    WORLD_OBJECT_MESSAGE = "008"
    HEALTH_MODIFIER_UPDATE = "006"
    SEARCH_LIST_ELEMENT = "005"
    CRAFTING_RESULT_DESCRIPTION_BY_CLIENT = "004"
    CONTAINER_ITEM_CLEAR_CONTENT = "003"
    CONTAINER_ITEM_CONTENT = "002"
    CONTAINER_OPENING = "001"
    CONTAINER_CLOSE = "000"
    BOX_CONTENT_TO_CLIENT = 'BCT'
    NEW_CONNECTION_MESSAGE = "NCT"